Include video tutorials, modify commands and change their order in op…
OpenVidu/openvidu.io-docs pull request #46
Opened 2021-05-25 14:08 UTC by DavidRodriguezRay

…envidu-tutorials

2021-05-25 18:03 UTC, j1elo commented
@pabloFuente sobre esto
```
git clone https://github.com/OpenVidu/openvidu-tutorials.git -b v2.17.0
```

¿no os interesa mejor tener un "placeholder" que luego reemplace un script? Por ej.
```
git clone https://github.com/OpenVidu/openvidu-tutorials.git -b v|OPENVIDU_VERSION|
```

eso haría las releases más "seguras" (menos probabilidades de dejarse un tag por error)

Por ej:
* [VERSIONS.env](https://github.com/Kurento/doc-kurento/blob/2105990eb849de857a4a9dd0127b471a8d264536/VERSIONS.env#L19)
* [configure.sh](https://github.com/Kurento/doc-kurento/blob/2105990eb849de857a4a9dd0127b471a8d264536/configure.sh#L54)
* [Texto donde se usa](https://github.com/Kurento/doc-kurento/blob/master/source/user/installation.rst#docker-upgrade)

2021-05-25 18:11 UTC, pabloFuente commented
Las instrucciones de release para actualizar la doc ya tienen en cuenta el tag de release. Al final lo que hay en master es la ultima release, asi que digamos que el placeholder es el numero de la release desde la que se actualiza, si quieres verlo así 😉

La cosa es que no hay un script super automatico que actualice la doc de un golpe. Hay unos pocos pasos de reemplazo que se hacen a mano (yo siempre lo.he hecho desde el vscode). Porque además luego puede pasar que haya que hacer ciertos ajustes manuales que no caen dentro de una posible automatización completa.

2021-05-25 19:30 UTC, CSantosM requested changes

2021-05-25 19:30 UTC, CSantosM commented on docs/tutorials/openvidu-electron.md
> +<center>><iframe width="560" height="315" src="https://www.youtube.com/embed/Hq_5wmCpDjY" title="YouTube video player" ?rel=0 frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypte
I would suggest you using css styles instead of `center` tag for video alignment. It's a better practice. 

I also want to warn you about the `?rel=0`. This is not an iframe property but it's a video url param that you can embeed into it, for example, `src="https://www.youtube.com/embed/Hq_5wmCpDjY?rel=0"`

These comments apply for all videos

2021-05-26 20:22 UTC, CSantosM approved these changes

2021-05-26 20:24 UTC, merged